using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CordsTry
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string SOWN = "OOWNWSNWWNWWONOSOONWSWNNOWSSWOWNWOSNOSSW" +
                "NONONSOWOSONWNSNNOWWNOWSNWOOOWWSNNSONOOWNNWNSNSONNWOSN" +
                "SSWSNWONSONNNONNSSNNSNSNSWONNSNSNSOSWOWOONSOWNSWWONWWNNO" +
                "WONOWOWSOOSWOOSWSSNWNSWNOSSWNSOSSNWWOWWNSNONOONNOSONSOSNSW" +
                "WSOSONSOSSWWSWWSOWNOWSNNSONONOSSSSNNWSSNSWNOWSSWWSWNWNWWOWS" +
                "NNONWNWONOSWNONOWWSNSONOSWWWONOSNOONOWNSWWWNOSOSNWSSSOWSWOOSO" +
                "OSNWOWOWOOONNOSSSNOWOWSSNSNSOWONNOWNNSOWOOOSOSSONWONNNNNSNWO" +
                "NOOSWNWWOWNSSOWSWSSNWSNWWSOWSWNOSNNNSOWSSONWWWWOWOONSWOOSO" +
                "WSOWONSONNNSSNWWOSWSWWNSWSSSONOSWSNSOSWNWWWOWNSSOOSWWWON" +
                "OWNSOWSOWOONNSOOSWOWWNOWOSOSSWSWOSOSSWWWWNOOSOOSWWOOONO" +
                "WONNWOOSOWOWSOONONSWNONOWSSONOOWOWOOWSWNSOWOOSNWNOSWNN" +
                "NWWWOWWNSWONOONONSSNNNNNNSSWNOWWSSSNWNOWOOSONWNWNONNNOOWS" +
                "OSWOSSOSONOWNOWNSWOOOWNWWOOWWSSWSNSOSWONNOOOWOSWWWSSONWWWNN" +
                "WSOWWSNOSOOSSNONONSOWNWWSWOOSOSSWOOOWSNWSWOOSONWNOOSSSOSSOWWWS" +
                "SWNOWOWSSNSSWSOWWSSNNNOOWWONNONSONSNWOSSWNSNNWSWONOOOOWOSNWOO" +
                "OOONWNWWWWNSSSONNWSWOONNNSWOSWOONSWWNSWOSOSOWSNONOOWWNSOSNS" +
                "WSOSNNWOWSWSONNSSWSSWOSSNWOONWSNWSWOOSOOOSWOSNNNNWSNWNOSN" +
                "NSONSONNNSNSWNSONWSSSNWNOOSSWWSNSSSWSWSOOONOWNSOOOOONSW" +
                "SOONSOOOOSSWNSWWWSOWOSSNWONNWWOWONSONWWSNOWNNNOWWNNNNWWSS" +
                "WNOSNNWWWNWSOSNSNOSWSSOOOWSNWNNSSWWWOWOWSWWNOWNSWWNWNNSNNNWOW" +
                "OWNSSOOOOSOWSWSNNOOSSSWSSOWSOSOSNONNNWONNONWOSNWNSONOSOSSWSNWSNS" +
                "WSSWSSONONSNNWSWNNWSWOSSNWNOWSWSSOWOOWWONWONNSOSNWSONONSWOWNSWWOS" +
                "OSSONONNOWSOWWSNONNWSSONNSWSSWSSSWNOOWNNOWNWNWNSWWOOWNSSSOONNSNONWNN" +
                "SSNSOWSSWWWONSWSWSNSONWOWNOSSWOSSOOOWSONOSWSSWSONSWNNNWOOOWNNSWSWS" +
                "NSSNWSWWONWOWSNSSWWWWSNNWSNWWNNSNNNSSWNOOSSSWNWNOSNNONSSSSWNSWOS" +
                "WOWWNOWWWNNSSOOSWSWNWOWSOSNOWSSOWSONNWWWSSWWNSSSSOONWNSOONSOS" +
                "SNNNWSWNNOSSOOSNONSNSSNNWNWOWNWWONONWNWWSSSOOONSOOSSNOONON" +
                "OOWSOOOOOWSOSNSSWSNWSOOSSWNNSSWOSWSSOONOOSNOONNNOWOSWSSWN" +
                "SSONWWSONSOOWONNWNWOSNNNSONWWSNNOWONOWNSOWOOWNSWWWWSSNWWSWO" +
                "OSSSSNSNNNNNOOOWSNNNNNWSWOOSWWNOSONNNSWOOWSNNOWOSSOSOSNSOWNNWN" +
                "OOOOSONWOWSWOOOSWSSSNNOONOSOOSOONSWNWWSOWSSWSWWSWWWOWSSONOWWWNNSSOO" +
                "ONONONNOWNSSOOWNOSOSOWSWWOOOSWOOSWWNWNONSWOSSSWWWNNNONNWNSWNOOWSWN" +
                "WWWNWSNSOOWOWWWONWNNNOSNSWOWNWWONWNWONOOWSWSNSONOWWNSNSONONSSONO" +
                "SOONWSOOSONWNNSNWNOOOSSONSOSOSOOWSSNSNNONOONOWWOONWSWSWOWONSNWWSWNOW" +
                "WWOSOSOWSWSNNONNWWNWWWNSWNOWNOWWWNWWNWSWSSNOWSSSOSWNSWWWNWSWSSWOSWONO" +
                "OOOWOSOWWWNSWSWSSNSOONNSOSNSSNWWOSONSNNWNWOSSOSNNSSOOWSNONOOOWSSNOWWSWSW" +
                "NWOSNWSWOONWWWSWSWNSSSNSSNSWWSNSNNOSSWOOSWNWONWNOSSOWWWNNWWOWOSOSSSNWNOOSONW" +
                "SONWWONWWWWONWWSNWNSONONSOOWONSSSNSNSNNSSONSSWSOWSSWWNNOWWSNWSWWSOOSSSWWO" +
                "SWSNONWNSSOONWOOONOSSNWSONWOOOOSOWWNOSONWONWOSNSWWNONOOSSOWNWSNSOWNWNSO" +
                "WWSNWOWONWSWOSOWWSSSSWWNNNOWSONSOWWSNNOSNOWSWOSSONNONWONSSONONOONOSOOS" +
                "WNSONNNNNSSWNONSSNSOWWWNSNNNNOONNNSNSOOWSNSSWNNWOWSONWOWSSSONWSNWOS" +
                "NWWWWOOWOWNWOOOWNNNNNSONNSWONWWONNSWSOONWSWSOWOONOSSOSSSSOWNNOWONOSW" +
                "SSOONWNNSNSNNNWOWOWWONNNNOOSSNNNWWSOSOONNOOSNONOOSWSOOWWSNWOWOOOSSWNWNSNONN" +
                "NOONNOOWWOWNSWNOWONNOSNSOWNOWNOSNSNWOOONSNOWNOWWWSSWOSSSNOOOOWNNOOOSWOWOWON" +
                "SOSOSNSWSOOONSNNWWOWWWSSWOSOSOWONSNOWSONWOSSOSNNOSONWSSNNSNSSOSOOWSWONNNOOSSON" +
                "SNSNWNWNONNSSONWWWSWSNWSSONONNWOSSWSOWWWSSWWWSSNNNWONWSNWOWWOSOOWSSSOWNSWWN" +
                "WNNNWWNWWWNOSSNSSSOSNOOOOONWOOSOWNSWSONNNWWSONNSNNOSNWOOSNSWNNWSSWOWOSSONNSOW" +
                "ONSOSSSOWNNOOSNWOSWNOSNONNOWSOOWSSWWOOONNSNSSWNNWWOOWOSWOOSWOWWWONOSOOWS" +
                "NNWSNSOSNOWWONONWOWSNWOWSNWNNNOOWWNWSOOWOSSWWNNSWNWNSOSNWWOSOOWONWNONOWWNWSOOW" +
                "NOSOWNSSWOWWNWWNWNSNWSOWSWSWNSSWSNONSSOWSWWOSWWOSWWWSNONNNOOWWNNWNWOOOOO" +
                "WWSSNNNWNOOSWSOSONWNWNWWNSOSSWOWSOWWSOSONWSSWWOSWWOSOWWWOOOOSNWSWOSWSWSWWWWWWW" +
                "NOWNNWONNOSSNSNOWOOONONNSWWWNOONWWNWWSOOSNONWWNSSOSWNWSWNWOOWSSSNOWWSSWNSNNNNOOSSWWO" +
                "WSOSOWWWWNWNOOWSSOONOSNSWOWNSSOWWSOWONWONNOSWWNNOOOSNSWNNOOSOONONOSSSWSNOSWWONOOO" +
                "OSONSWWNNWNOONNWWSSSNNWSOSWSNSWSSSNNSSNNOWWONSWOOSNONSOOWWWSWWWSSWNNSWOOWSNNO" +
                "ONOWSNWSOONOOSWSWOOWNOOWSOWWWNSOSSWOSONWSSOOONOSOWOOSWNSNSOWONONOWOSOWSONWSOOSOW" +
                "SWNSOWNNNOSSSSSOOWWNNOONSWSOONONWOOWSNOWSOSONNNWOWSWSSWNWWOOONOWSNOWNNSSWNWOWSSNS" +
                "WOOWWSSSNONNNNOOSWOWNSSWNNNNWOOOSONSSWNWNWNNWOSSSWWNWWOWWOWONSOSNWSONNONOOWNOOWSO" +
                "NSWWOOWOOOSNWWONOSOOOOOOOOWNNOOSNSSSWWOSNOONWSOOSWWONWNSWNNNNWWWSONNNWSWWWSWNSWSW" +
                "WWNNWOONONWSNSSWNWSNSOWSOSNOOSOWWWWOWSWNWSSWSNOSWWWNWONSOWOSSONSSWWWWSWSSWWSWNNSWN" +
                "NOSSOOSONOWSNSONSNOOWSWOWOSOOSWSSSNOWWNWWSWSOWOWNWNNSWWSOOWSSOSNNSOWWNSONWSSWSWSNWN" +
                "WWNNSSNOOOWWSWOWOSNWOWONOSOOSOOSWOSWOOSNSONSOOOSONSOONWONWSSWOSSSSNWOSNWNWWNSOOWWWN" +
                "OOSSSNWONNNOSWSSSNSSWNONNSOWSSONNSSOSOSNSSWSNSOWSWSNSWSNNSNNNWSOWWSWNOOSOSSNNSOWOSSN" +
                "NWOSWSWOSSWONWSWOWWNONNOSOSSSWSWSOOWONWNOONWOSOOWSSSOWWNWOONNSWOSSNOSWONSONNNSNNWWOO" +
                "NONWWSWNNWWSWWWNNSOSWWWWOOWNNSOSWSOSNNNWSNSWWSOWWNOOWWSWNWSSSWNWWWONWWWSSOSSNWSNSOSO" +
                "WNWWNNNOWNWONSSWWSOOOSWNWONWWWOOSONNOSWWSNOSNWSWWOWOWNNONNOOOWNNWNOOSWSONSONSONNNWWNN" +
                "OSOSNWWWWOWSSSWWWWOWWONWOSONWONNSWSWWNSSSNNOWNNSNSWSWNSWNNNWSSOOWWSOSSWNWOOSNONOOOWWSS" +
                "SWNNNNWSNSSWNNONONSNWSSWNNOWWSNNOWWOSONWOONSWNSNNSNOWNOOWNSWNWSSOSWSOWSSNSOOSSSNSSSNON" +
                "SWSWSOWSOOSNOWONNWONWNSWNNOOSSNNSNWOSNOWSSSWNWWWWNSSSWSOWSNNWWONONSNOWWOWSNNWSSWONWSWW" +
                "SSSONOWWWSNOONOSSNOOSSOWOOOOSSNNNNSONOWONOWWSSSOWWSWOSNONOWNNSWNONSNWNSSOWNSSONWOWSSO" +
                "SOSSSSWWSONSSNNOSOOWNNOWWSWWNSONWONWWNSWSOSOWSSSOSOWONSWOWNONWWONSOONOSWSWOWW" +
                "WOOWWWOSOWSWSNNWOONSSSNWSWSNWSSNWWWOOWNWNOWSSSSWOONONSWOSONSSSNNSOWONWSSWOOSSN" +
                "WWOOOWWWOOWNNSWOOSWOWSWNWWOONONWOWOONWONNWSWWONSOONNWONWWNOWSWOOOWWWWOSONWWOSW" +
                "NWNSSWWNWOWSOWNSNNOSONONSWOSOONNOOSWNSSOOSWNSSONONNWOONWNWNWSWSOWOWOOWWNOWSOWWWN" +
                "NWSSOONOSSNSNNNSNWSWWOWSWOSONSSWWSONSWOSSWSOONSWNNSSSSOSSOWSONOWNNNONOWSWOWNNNNWS" +
                "NONSNWWNWWWOWSOOWNNNSNOOOONOSWNWSNOOOWOWSOSOOSOSWNSWOSSSNOOSNSNWWNSSOSNSNWWOOWOOSS" +
                "NWSNSWSNNNNNOSSOONNNWONONSSWOSSOSWSNONSOWSNNNSONSSSNSWOOOSNWOOSOONNNWNSWWOSSSWSWNWS" +
                "SSNNOOSSNOSOWOWSSONWNOOWOOWSNNONNSNSONSSONNOONSNOWSSWWNSNOOWSSNSWWWNONSNSWONOSWWWWSSS" +
                "WNSOSOOSSSONWOWSWNOOSOOWONSNNOSWOWSSOSOSSWSWWOWOSSWNWSOOWOSSOWWSNNNSWNOOSSNSWWNNWNSWSO" +
                "OONWWSONWNSOOWWNOWOOSWSNWWONSNSONOWWOSWSSWOSOWNSNWNWSNSWNWSOONSNWSNWNWWSSWNWWONWOWONOOSO" +
                "SSNOSNSSNWSOOOWNSONOOWNNOWSWWOWOSWNONSOOOOWSOWOSWSNWNONWNWNOSNWOONWNNWSWSOOSWNSOSSWWSNWO" +
                "WWSOSONOWSWSOSWOOOOWWWOWWWWWSOWOONWNWNONWOSNOWSNWNNWONWSNSOOWNOOWNNWSOWWONNWWSNSOWONS" +
                "ONOSSSWWONNOWOSWNWWSSNNOWOOOSSNNWONSSWWSWONNONNOSSWWNWSNSNOWNSOSNSSWWNWSOOONNONSWWWNNO" +
                "WWWSWSWOWWNNNWONSWOONNWWOOSOSSNSNOSONOONNNSWWNWWWSWSONSWWWSNWNNWNNOSOSSNNSWWWNNNNSSNON" +
                "WWSOSSWOONSOOSOSWNWNONOSWSSOOSNSNOOOWNNWWWSWNSOOWSNNSWOSWNSNWSNNOWWSOWWSWOSWOWWWNSWWNWNW" +
                "SWONNOOSSSONSSNNNWWNSOONSWOWWNOSWOOSNSNWWNWOWOWOWWWOWNOSWWNNSWWWWNWOSWWWNWNOWNNSWSWONOSO" +
                "SWSNOWNNNNSWSSWONOONSWWSWNNWNNSNWNSONWOWOSOOWNOWSSSNSWSOWWSWOOWSSOOOOOONSOSONWNNOONSOS" +
                "NOSNONNWONOSNOWWNNNNNSWSNOSWNSSSWWSWOOSOOWWOWSSOOOSNWWNONONNONWWWWWSWWOWNOONWSNNSWWWWSO" +
                "SOSNNSNNOOOSSONSOWONWOSSSNNNOOWSNSNNWSSOSSOOSWWNNSNSNSOOWSOSSSONSSOOONNSSOSWOWWSOOWSSNNN" +
                "NSNOSSNWOOSSONONNOSSNWSSNSWSWSOSSSSWSSSNNWWWNWNOWOOSNWNOOOOWSNNOSSSNNWOSNSWWWNOOSSNSSSNW" +
                "WWNOOSOONNNWSWSOOSWWWNWNNWOSOSWWSSNWWSONSSNSWONSWNNWONNWSWOWNWNOSWNWSWSWWNWNWOSSSOWNSSOWNW" +
                "SSSOOOWSNSOOOWONONOSSNSSSWWOWSWNNNSSONNSNOOWNSOSNWWWNSSNONSWWOONWNNWSSONSNSWSNSSOSSSNNNOWWS" +
                "OONOONNWNSSNSNNOWNWSOOONNSOSOWSSSONSWOSOWOSWOSONWNOOSWNNWWNNWSOOOSWWWSWSSSNNSWSWWNSSOONOONSWON" +
                "SONOOSSOONNNSSSOOONNSWONWWOWSONNNSSWSWNOOWSWSONNWWNSONNSOWNOOWOOWOSWSWSNNSNNOONONSOSWSWNSOSNOOO" +
                "SSWSSNSOWNSSSSWNOOWWSSWSOONOSSNWNONWNNSNNNNSWNSNOSOSNNWOWWSNWWSNNWOSWOSSWNOWNNSNSNSWONSNWSONNW" +
                "SOOWSONSWSSWONOOSSOOWNOOWOWOWWOWWOONOOWOSSWSONOSWWSSWSSWONNNSOOOOSNSOSOONSNWSSSSOSNSWWOWOOSOOWO" +
                "WNONNWSOSSSSNNONNWNWNOOOWOSSSWOWSOSNNWSSWNSSSNOOSWNNWSOWONNWNONOWOSNOSNOWSSSOWONWNOOWOWNOSNOON" +
                "SWWNNWSWSSSSSWOWOWONSONSWWOSWSONSOWWWOWWWOSOWONNONOOSWNNOSSNSSSOWSSSSNSWONSOONWNNWWOSNONSWSONW" +
                "OWOSWSSONSSNNWOONNWWSSSONWOWNNSSSOSSNNSNOOSOWSNSOWOWOWWNSWONNWOSOWNWOWOOWNSWNOOSWNNNNOSWNSSNNON" +
                "WNONNWNNOSSSWOWNSONSNOSNNWWNWOWOSNSWSNNNSONNWOONONSWSWSSOSSNOWOSNWNOWWSSSOWNSWNWSSNWOONSSNWOOWO" +
                "ONNSWWOSSNWNONSOSOWNWWNWNSSWWWSWOWSNOWNSWONOWSSSWWNNSNWSWSONWNWNNWWWSWOOOOSSNONWSNSSONONNSSWWOW" +
                "OONOSOWOWONSOOONSNNSWOSOSSOWNSOSWWWNNNONNNWNWNONNNOWWOSSNNWSOWNSONONNNSOOWNWONSWOONSSWWOWWWONWOWSOOSNNWWNNSSNOSNSOOWWNSNSWWNNSWSOWSOSWNOWWSOOWNNSWOOWNSOSNSNNSOWWWNOOOOSSSNNNWSSWONSNOONNNNOWWOSOWOWWWOWSOOSWNSONOOONNNWSOOWSSNWNNWSSSNOONOSNNSOSONSNONWWOWSWWWSOOONSSNWWWOWNSWNWOSOWNSOOOOWWWNOOONONWWOWNWWNNONSNWNNONWNSSNOONOSOONSONOOSWSSSNSOONONSOOOWWNWOSNNSOWWSOSNSWNNWSSNOWWSOSNNOSOOOSOWSNONOSNNWSNOOSSNWOOWNNNWONSNSNSSWWNNWNSOWSSNWSONWWSWNNWNNSNOOWSSNOOSONSSNNNWSSONSSOOOOSWONSNSSNOWOWSOSNSSOOOOOONWSNWONOSWSNNSWNSWSWSSSOSOWSOWNNWWOWWOOWONNSNWWSOWNWSWWONNSOWNOWSNOWSOWWSOOONOOOWSWNSNNWWSOONNSSNNWWNNWWONNWWOSOOSWSONWONNONOSNWNSWNNWWSONNSSSWONOWSOWNOOONOONWNSWSNSWOOWSOSSOWNSSSSONNOOOWSOOWWWSSWWWSWOWNOOSNNSONNSWNNNSSOSOSNNOSONNOSNSNWOONNWSOSOOOSOOSWSSOSWWOONNOWOONSWWNWWWOWSOOOSNWWWWONOWOONOOWWNSNONSOOSNNOWNWNOWONSWWWNWNNSSWONNNNSOWWNOOSNONOSSSSWNOWWONOOSONSSNOOWNSOSSSONOWOWWNWWNWSOWNNOSWSSOOWOOOSNNNNNWWNWWSSWWWNSWSSSSNSSWNNOWSOSOOOSWSSNOOWSSSNWOONNSSSNSNOONNWOWNWOOWWSNNSWWWWNWSWSWNWSOWSSSWSWWNSONNNOOWONSOSOOSWWSSOWNOWNOSSOOOWOWOWNNOSSONWSWWOOWWNONWSNNOSOOOSSOSSOOSONSONWONNONSNNSSNSSNONNNSSNOSWSWSNSNSWNSNWONWOSNNNOSSOSOOSSWWSWOWWOSNSNONWWOSNOWNWSWSWSONOOOWSONNONOWWONSWWONNNONWOWWSWWWWWWNNSSWSSSWOOOSSWOWSONWOWSWSNOONWSWSSOWOWSWOWSNSWSSSONNWWOWOSSSWWNWOWSOWOONOSOWWWSNWOWSNWONNSOWSOOWSSNOWOONONNSSSSWOSNOWSWWOSSWWOWNWSONNSWWNSOOONNOOWNNWWOOWWNONNWWNWNWNNOWSONSNOSNOOSNOOOOWOWOOWNWSNNNOWWNNWNNNNNSOSSWSWNSWWNWNNOOWWNNSNWWNOWNWWNWSNSSWNOSOSWNSWWNNONONONWWNWWOONSSSNSWNNOWNNNNSNWNOOWWOWWONSWNWSWSONSNNSWOOWSWSNSOSOSNWSWONSONOWWNOSOWWWNNSWOSOWNOSSWONOSSOSONONNOWNSSWNSSWSNNNNNWWOWOOWSSWNONOWNWSWONNWONWWSWWNNONWOOSWSSONOWOSNWSWWNONNNWWNNOOWNNWOWOOONOONSNSOSNOSSWONWNSOWSWWWSNWSWNWOSNNOOWSOOOSWWSSWSSWSNSONSSONONSOSWNOWNWNWONNNWSSOWNSOWOWSWNONNNOOOWOONOSNNWWNOOWOONSNOONNNOWONNWSNOOSWSNNOSSNWWSWNNWWOONNWNWOSOSWSNSSOOSWONNOOWSWWWSOSSNWWWONWOOOOWWWSWWSOWONWOSOSONOOOOWSWSOSOONNWSSONWOSSWSSONWSNSOSWSOSNWOWOOWNNSSSSNSNSSOONOWSOWSOSOOWOSWSONNNNNNWWNONNSNOWOWWWSNOWWNOOOOSWSSWWNWSNSNOSNWWSSWOOSSWWWNWONNOSWWNNOOSWOWSWOONSNNSSWOWSWSNSWNNSONWSSOWNWNSNONONWWSOWOSSWWWNOWNNNONNONNNWOONOWSWNOONWONSWNWSSWWWNWSWSWNSNWSOOSWOSWSONWOONOOSONOWNNSWWWOSSWWNONSSSSOWSOSSNOWSONSSOOONSOWNSOONSWNSSNNNNNOSNNSNSWSOSNNSWSNWSONNONOONWSNOSWOWWNSSWNOWSSSWSSOWSNSNWSSSSOWWWWNWNWOWOOOONNWSNOSNSONSOWNOSSNWWONWSSNNSOWSOSOSOSNWNSNOOSOWWNSSWNNONSWNNWWSSSNOSSOSOOOOSNNWOSNWNWNWWNSOSSWSSWOSSWONOWSWSWWOWONOSSOSSWNOWWNNWNNOOSNWWWWNNOWWSWSWWWOOOOWWWWNNNWSNWSNNNNWSNNWSSOSSWSWWSNOONWNSONOOOONOOONWWWNOOONWWSOONWWOWWSOWSOOOSNSNOWOWOWNSNNNONNOSSWSWW";

            //Im tired now

            char[] b = new char[SOWN.Length];

            Console.WriteLine("Здесь " + SOWN.Length + " символов");

            int x = 0; //vostok  O = +1 W= -1
            int y = 0; //sever  N = +1 S= -1


            using (StringReader sr = new StringReader(SOWN))
            {
                {

                    sr.Read(b, 0, SOWN.Length);
                    Console.WriteLine(b[1]); //first symbol of array (checker)

                    for (int i = 0; i < SOWN.Length; i++)
                    {
                        switch (b[i])
                        {
                            default:
                                Console.WriteLine("По новой, не понял");
                                break;
                            case'O':
                                x++;
                                break;
                            case 'W':
                                x--;
                                break;
                            case 'N':
                                y++;
                                break;
                            case 'S':
                                y--;
                                break;
                        }
                    }
                    Console.WriteLine(x+ " " + y);
                    Console.ReadLine();
                }
            }
        }
    }
}
